### ISSUE TITLE
ESPHome

### ISSUE THREAD

**Issue by Holewijn** [jomjol/water-meter-picture-provider#2]
Hey, may i ask how we can use this with esphome? :) and not Arduino

**Comment by vigne** [comment]
simply put, you cant. You can either install esphome using the esp32cam platform (https://esphome.io/components/esp32_camera.html) to integrate into HA, or, if you wat to use this software, define a generic camera (https://www.home-assistant.io/integrations/generic_ip_camera/) in HA using the "still_image_url" property.
